# Generated by Django 6.0.4 on 2026-06-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meetingrecording"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
